version: '3'

networks:
  app-tier:
    driver: bridge


services:
  rabbitmq:
    build: .
    container_name: rabbitHGH
    ports:
      - 5672:5672
      - 15672:15672
      - 1884:1884
    environment: 
      - RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq.conf
    networks:
      - app-tier

      
  
  # myapp:
  #   image: 'YOUR_APPLICATION_IMAGE'
  #   networks:
  #     - app-tier