version: '3'

networks:
  app-tier:
    driver: bridge

    
services:
  queue:
    build: rbmq/.
    container_name: rabbitmq
    ports:
      - 5672:5672 
      - 15672:15672 
      - 1884:1884 
    volumes:
      - "C:/Users/hosse/Docker/Rabbitmq/rbmq/Conf/:/etc/rabbitmq/"
    networks:
      - app-tier

  consumer:
    build: sl/.
    container_name: stl
    volumes:
      - "C:/Users/hosse/Docker/Rabbitmq/sl/log/:/usr/src/app/log"
    networks:
      - app-tier
  cache:
    image: redis:latest
    container_name: redis
    ports:
        - 6379:6379
    volumes:
        - C:/Users/hosse/Docker/Rabbitmq/redis/config/redis.conf:/redis.conf
        - C:/Users/hosse/Docker/Rabbitmq/redis/Data:/data
    command: [ "redis-server", "/redis.conf" ]
    networks:
      - app-tier
