version: '3'

networks:
  app-tier:
    driver: bridge


services:
  rabbitmq:
    build: .
    container_name: rabbitHGH
    ports:
      - 5672:5672
      - 15672:15672
    environment:  
      - RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq.conf
      #-RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error}]
    
    networks:
      - app-tier
  
  # myapp:
  #   image: 'YOUR_APPLICATION_IMAGE'
  #   networks:
  #     - app-tier